-- XPETIS · seed 0002 · Tassonomia geografica
--
-- GENERATO da supabase/scripts/genera_geo.mjs a partire da
-- xpetis_destinazioni_v2.json. Non modificare a mano: rigenerare.
-- Attese: 6 continenti, 14 macro-aree, 129 stati, 244 regioni, 188 città.

-- Regole di selezione dichiarate dalla tassonomia
-- (le regioni italiane NON filtrano: deviazione 7 del PIANO, confermata il 27/09/2026):
--   selezionabili: macro_area, state, italian_region
--   solo cercabili: continent, city, foreign_region
--   Cercando 'Italia' il sistema suggerisce le 20 regioni italiane (tutte selezionabili).

-- Tutto in una transazione: rigirato sopra dati esistenti, un giro fermato
-- da una guardia non deve lasciare mezza potatura.
begin;

-- Guardia: nel database non ci devono essere continenti, macro-aree, stati o
-- regioni che il file non ha. Non si cancellano da qui (uno stato ha dietro
-- td_countries e quiz_responses): si ferma tutto e lo si dice.
do $$
declare v_extra text;
begin
  select string_agg(x, ', ') into v_extra from (
    select 'continente ' || code as x from geo_continents where code <> all (array['europa', 'africa', 'asia', 'americhe', 'oceania', 'antartide']::text[])
    union all select 'macro-area ' || code from geo_macro_areas where code <> all (array['europa_est_e_caucaso', 'europa_nord', 'europa_sud', 'africa_sub_sahariana', 'isole_delloceano_indiano', 'nord_africa', 'asia_centrale_e_subcontinente_indiano', 'asia_orientale_e_sud_est_asiatico', 'medio_oriente', 'centro_america_e_caraibi', 'nord_america', 'sud_america', 'oceania', 'antartide']::text[])
    union all select 'stato ' || code from geo_countries where code <> all (array['armenia', 'azerbaijan', 'bielorussia', 'georgia', 'moldavia', 'russia', 'ucraina', 'austria', 'belgio', 'danimarca', 'estonia', 'finlandia', 'francia', 'germania', 'irlanda', 'islanda', 'lettonia', 'lituania', 'lussemburgo', 'norvegia', 'paesi_bassi', 'polonia', 'regno_unito', 'repubblica_ceca', 'slovacchia', 'svezia', 'svizzera', 'ungheria', 'albania', 'bosnia_ed_erzegovina', 'bulgaria', 'cipro', 'croazia', 'grecia', 'italia', 'kosovo', 'macedonia_del_nord', 'malta', 'montenegro', 'portogallo', 'romania', 'serbia', 'slovenia', 'spagna', 'turchia', 'botswana', 'capo_verde', 'costa_davorio', 'etiopia', 'ghana', 'kenya', 'mozambico', 'namibia', 'nigeria', 'rwanda', 'senegal', 'sudafrica', 'tanzania', 'uganda', 'zimbabwe', 'madagascar', 'mauritius', 'riunione', 'seychelles', 'algeria', 'egitto', 'libia', 'marocco', 'tunisia', 'bhutan', 'india', 'kazakistan', 'kirghizistan', 'maldive', 'nepal', 'sri_lanka', 'uzbekistan', 'cambogia', 'cina', 'corea_del_sud', 'filippine', 'giappone', 'indonesia', 'laos', 'malesia', 'mongolia', 'myanmar', 'singapore', 'taiwan', 'thailandia', 'vietnam', 'arabia_saudita', 'emirati_arabi_uniti', 'giordania', 'iran', 'israele', 'libano', 'oman', 'qatar', 'belize', 'costa_rica', 'cuba', 'giamaica', 'guatemala', 'honduras', 'messico', 'nicaragua', 'panama', 'repubblica_dominicana', 'canada', 'stati_uniti', 'argentina', 'bolivia', 'brasile', 'cile', 'colombia', 'ecuador', 'paraguay', 'peru', 'uruguay', 'venezuela', 'australia', 'fiji', 'isole_cook', 'nuova_zelanda', 'polinesia_francese', 'samoa', 'tonga', 'antartide']::text[])
    union all select 'regione ' || country_code || '/' || slug from geo_regions
     where (country_code || '/' || slug) <> all (array['armenia/armenia', 'azerbaijan/azerbaijan', 'bielorussia/bielorussia', 'georgia/georgia', 'moldavia/moldavia', 'russia/russia_europea', 'russia/siberia_e_estremo_oriente', 'ucraina/ucraina', 'austria/vienna', 'austria/tirolo', 'austria/salisburghese', 'belgio/fiandre', 'belgio/vallonia', 'belgio/bruxelles', 'danimarca/selandia', 'danimarca/jutland', 'estonia/estonia', 'finlandia/finlandia_meridionale', 'finlandia/lapponia_finlandese', 'francia/île_de_france', 'francia/provenza_costa_azzurra', 'francia/normandia', 'francia/bretagna', 'francia/alvernia_rodano_alpi', 'francia/nuova_aquitania', 'germania/baviera', 'germania/berlino', 'germania/renania_settentrionale_vestfalia', 'germania/amburgo', 'germania/sassonia', 'irlanda/leinster', 'irlanda/munster', 'irlanda/connacht', 'islanda/reykjavik_e_sud', 'islanda/nord_e_ovest', 'lettonia/lettonia', 'lituania/lituania', 'lussemburgo/lussemburgo', 'norvegia/norvegia_meridionale', 'norvegia/fiordi_occidentali', 'norvegia/norvegia_settentrionale', 'paesi_bassi/olanda_settentrionale', 'paesi_bassi/olanda_meridionale', 'paesi_bassi/utrecht', 'polonia/masovia', 'polonia/piccola_polonia', 'polonia/pomerania', 'regno_unito/inghilterra', 'regno_unito/scozia', 'regno_unito/galles', 'regno_unito/irlanda_del_nord', 'repubblica_ceca/boemia', 'repubblica_ceca/moravia', 'slovacchia/bratislava', 'slovacchia/alti_tatra', 'svezia/stoccolma', 'svezia/lapponia_svedese', 'svezia/götaland', 'svizzera/romandia', 'svizzera/svizzera_tedesca', 'svizzera/ticino', 'svizzera/grigioni', 'ungheria/budapest', 'ungheria/transdanubio', 'albania/albania', 'bosnia_ed_erzegovina/bosnia_ed_erzegovina', 'bulgaria/bulgaria', 'cipro/cipro', 'croazia/dalmazia', 'croazia/istria', 'croazia/zagabria_e_continentale', 'grecia/attica', 'grecia/isole_cicladi', 'grecia/creta', 'grecia/isole_ionie', 'grecia/peloponneso', 'italia/abruzzo', 'italia/basilicata', 'italia/calabria', 'italia/campania', 'italia/emilia_romagna', 'italia/friuli_venezia_giulia', 'italia/lazio', 'italia/liguria', 'italia/lombardia', 'italia/marche', 'italia/molise', 'italia/piemonte', 'italia/puglia', 'italia/sardegna', 'italia/sicilia', 'italia/toscana', 'italia/trentino_alto_adige', 'italia/umbria', 'italia/valle_daosta', 'italia/veneto', 'kosovo/kosovo', 'macedonia_del_nord/macedonia_del_nord', 'malta/malta', 'malta/gozo', 'montenegro/montenegro', 'portogallo/lisbona_e_centro', 'portogallo/porto_e_nord', 'portogallo/algarve', 'portogallo/madeira', 'portogallo/azzorre', 'romania/transilvania', 'romania/bucarest_e_sud', 'romania/moldavia_rumena', 'serbia/serbia', 'slovenia/slovenia', 'spagna/catalogna', 'spagna/andalusia', 'spagna/madrid', 'spagna/paesi_baschi', 'spagna/isole_baleari', 'spagna/isole_canarie', 'spagna/galizia', 'turchia/istanbul_e_marmara', 'turchia/egeo', 'turchia/mediterraneo', 'turchia/cappadocia_e_anatolia_centrale', 'botswana/botswana', 'capo_verde/capo_verde', 'costa_davorio/costa_davorio', 'etiopia/etiopia', 'ghana/ghana', 'kenya/costa', 'kenya/safari_e_interno', 'mozambico/mozambico', 'namibia/namibia', 'nigeria/nigeria', 'rwanda/rwanda', 'senegal/senegal', 'sudafrica/capo', 'sudafrica/nord_est', 'sudafrica/kwazulu_natal', 'tanzania/continentale', 'tanzania/zanzibar', 'uganda/uganda', 'zimbabwe/zimbabwe', 'madagascar/madagascar', 'mauritius/mauritius', 'riunione/riunione', 'seychelles/seychelles', 'algeria/algeria', 'egitto/cairo_e_nilo', 'egitto/mar_rosso', 'libia/libia', 'marocco/marocco_imperiale', 'marocco/sahara_e_sud', 'marocco/costa_atlantica', 'tunisia/tunisia', 'bhutan/bhutan', 'india/india_del_nord', 'india/rajasthan', 'india/india_del_sud', 'india/goa_e_kerala', 'kazakistan/kazakistan', 'kirghizistan/kirghizistan', 'maldive/maldive', 'nepal/nepal', 'sri_lanka/sri_lanka', 'uzbekistan/uzbekistan', 'cambogia/cambogia', 'cina/cina_orientale', 'cina/cina_del_sud', 'cina/cina_dellovest', 'corea_del_sud/corea_del_sud', 'filippine/filippine', 'giappone/honshu', 'giappone/hokkaido', 'giappone/kyushu_e_okinawa', 'indonesia/bali_e_nusa_tenggara', 'indonesia/giava', 'indonesia/sumatra_e_borneo', 'indonesia/sulawesi_e_papua', 'laos/laos', 'malesia/malesia_peninsulare', 'malesia/borneo_malese', 'mongolia/mongolia', 'myanmar/myanmar', 'singapore/singapore', 'taiwan/taiwan', 'thailandia/thailandia_del_nord', 'thailandia/thailandia_centrale', 'thailandia/thailandia_del_sud', 'vietnam/vietnam_del_nord', 'vietnam/vietnam_centrale', 'vietnam/vietnam_del_sud', 'arabia_saudita/arabia_saudita', 'emirati_arabi_uniti/emirati_arabi_uniti', 'giordania/giordania', 'iran/iran', 'israele/israele', 'libano/libano', 'oman/oman', 'qatar/qatar', 'belize/belize', 'costa_rica/costa_rica', 'cuba/cuba', 'giamaica/giamaica', 'guatemala/guatemala', 'honduras/honduras', 'messico/yucatán_e_caraibi', 'messico/messico_centrale', 'messico/bassa_california', 'nicaragua/nicaragua', 'panama/panama', 'repubblica_dominicana/repubblica_dominicana', 'canada/canada_orientale', 'canada/canada_occidentale', 'stati_uniti/costa_est', 'stati_uniti/costa_ovest', 'stati_uniti/sud', 'stati_uniti/midwest_e_montagne', 'stati_uniti/hawaii_e_alaska', 'argentina/argentina_del_nord', 'argentina/patagonia_argentina', 'bolivia/bolivia', 'brasile/sud_est', 'brasile/nord_est', 'brasile/amazzonia_e_pantanal', 'cile/cile_del_nord_e_centro', 'cile/patagonia_cilena', 'cile/isola_di_pasqua', 'colombia/colombia', 'ecuador/ecuador_continentale', 'ecuador/galápagos', 'paraguay/paraguay', 'peru/peru', 'uruguay/uruguay', 'venezuela/venezuela', 'australia/australia_orientale', 'australia/australia_centrale_e_ovest', 'australia/tasmania', 'fiji/fiji', 'isole_cook/isole_cook', 'nuova_zelanda/isola_del_nord', 'nuova_zelanda/isola_del_sud', 'polinesia_francese/polinesia_francese', 'samoa/samoa', 'tonga/tonga', 'antartide/antartide']::text[])
  ) e;
  if v_extra is not null then
    raise exception 'Il database ha righe geografiche che xpetis_destinazioni_v2.json non ha più: %. Toglierle è una decisione, non una rigenerazione.', v_extra;
  end if;
end $$;

insert into geo_continents (code, name_it, is_selectable, sort_order) values
  ('europa', 'Europa', false, 1),
  ('africa', 'Africa', false, 2),
  ('asia', 'Asia', false, 3),
  ('americhe', 'Americhe', false, 4),
  ('oceania', 'Oceania', false, 5),
  ('antartide', 'Antartide', false, 6)
on conflict (code) do update set
  name_it = excluded.name_it, is_selectable = excluded.is_selectable, sort_order = excluded.sort_order;

insert into geo_macro_areas (code, continent_code, name_it, is_selectable, sort_order) values
  ('europa_est_e_caucaso', 'europa', 'Europa Est e Caucaso', true, 1),
  ('europa_nord', 'europa', 'Europa Nord', true, 2),
  ('europa_sud', 'europa', 'Europa Sud', true, 3),
  ('africa_sub_sahariana', 'africa', 'Africa Sub-Sahariana', true, 1),
  ('isole_delloceano_indiano', 'africa', 'Isole dell''Oceano Indiano', true, 2),
  ('nord_africa', 'africa', 'Nord Africa', true, 3),
  ('asia_centrale_e_subcontinente_indiano', 'asia', 'Asia Centrale e Subcontinente Indiano', true, 1),
  ('asia_orientale_e_sud_est_asiatico', 'asia', 'Asia Orientale e Sud-Est Asiatico', true, 2),
  ('medio_oriente', 'asia', 'Medio Oriente', true, 3),
  ('centro_america_e_caraibi', 'americhe', 'Centro America e Caraibi', true, 1),
  ('nord_america', 'americhe', 'Nord America', true, 2),
  ('sud_america', 'americhe', 'Sud America', true, 3),
  ('oceania', 'oceania', 'Oceania', true, 1),
  ('antartide', 'antartide', 'Antartide', true, 1)
on conflict (code) do update set
  continent_code = excluded.continent_code, name_it = excluded.name_it,
  is_selectable = excluded.is_selectable, sort_order = excluded.sort_order;

insert into geo_countries (code, macro_area_code, name_it, is_selectable, sort_order) values
  ('armenia', 'europa_est_e_caucaso', 'Armenia', true, 1),
  ('azerbaijan', 'europa_est_e_caucaso', 'Azerbaijan', true, 2),
  ('bielorussia', 'europa_est_e_caucaso', 'Bielorussia', true, 3),
  ('georgia', 'europa_est_e_caucaso', 'Georgia', true, 4),
  ('moldavia', 'europa_est_e_caucaso', 'Moldavia', true, 5),
  ('russia', 'europa_est_e_caucaso', 'Russia', true, 6),
  ('ucraina', 'europa_est_e_caucaso', 'Ucraina', true, 7),
  ('austria', 'europa_nord', 'Austria', true, 1),
  ('belgio', 'europa_nord', 'Belgio', true, 2),
  ('danimarca', 'europa_nord', 'Danimarca', true, 3),
  ('estonia', 'europa_nord', 'Estonia', true, 4),
  ('finlandia', 'europa_nord', 'Finlandia', true, 5),
  ('francia', 'europa_nord', 'Francia', true, 6),
  ('germania', 'europa_nord', 'Germania', true, 7),
  ('irlanda', 'europa_nord', 'Irlanda', true, 8),
  ('islanda', 'europa_nord', 'Islanda', true, 9),
  ('lettonia', 'europa_nord', 'Lettonia', true, 10),
  ('lituania', 'europa_nord', 'Lituania', true, 11),
  ('lussemburgo', 'europa_nord', 'Lussemburgo', true, 12),
  ('norvegia', 'europa_nord', 'Norvegia', true, 13),
  ('paesi_bassi', 'europa_nord', 'Paesi Bassi', true, 14),
  ('polonia', 'europa_nord', 'Polonia', true, 15),
  ('regno_unito', 'europa_nord', 'Regno Unito', true, 16),
  ('repubblica_ceca', 'europa_nord', 'Repubblica Ceca', true, 17),
  ('slovacchia', 'europa_nord', 'Slovacchia', true, 18),
  ('svezia', 'europa_nord', 'Svezia', true, 19),
  ('svizzera', 'europa_nord', 'Svizzera', true, 20),
  ('ungheria', 'europa_nord', 'Ungheria', true, 21),
  ('albania', 'europa_sud', 'Albania', true, 1),
  ('bosnia_ed_erzegovina', 'europa_sud', 'Bosnia ed Erzegovina', true, 2),
  ('bulgaria', 'europa_sud', 'Bulgaria', true, 3),
  ('cipro', 'europa_sud', 'Cipro', true, 4),
  ('croazia', 'europa_sud', 'Croazia', true, 5),
  ('grecia', 'europa_sud', 'Grecia', true, 6),
  ('italia', 'europa_sud', 'Italia', true, 7),
  ('kosovo', 'europa_sud', 'Kosovo', true, 8),
  ('macedonia_del_nord', 'europa_sud', 'Macedonia del Nord', true, 9),
  ('malta', 'europa_sud', 'Malta', true, 10),
  ('montenegro', 'europa_sud', 'Montenegro', true, 11),
  ('portogallo', 'europa_sud', 'Portogallo', true, 12),
  ('romania', 'europa_sud', 'Romania', true, 13),
  ('serbia', 'europa_sud', 'Serbia', true, 14),
  ('slovenia', 'europa_sud', 'Slovenia', true, 15),
  ('spagna', 'europa_sud', 'Spagna', true, 16),
  ('turchia', 'europa_sud', 'Turchia', true, 17),
  ('botswana', 'africa_sub_sahariana', 'Botswana', true, 1),
  ('capo_verde', 'africa_sub_sahariana', 'Capo Verde', true, 2),
  ('costa_davorio', 'africa_sub_sahariana', 'Costa d''Avorio', true, 3),
  ('etiopia', 'africa_sub_sahariana', 'Etiopia', true, 4),
  ('ghana', 'africa_sub_sahariana', 'Ghana', true, 5),
  ('kenya', 'africa_sub_sahariana', 'Kenya', true, 6),
  ('mozambico', 'africa_sub_sahariana', 'Mozambico', true, 7),
  ('namibia', 'africa_sub_sahariana', 'Namibia', true, 8),
  ('nigeria', 'africa_sub_sahariana', 'Nigeria', true, 9),
  ('rwanda', 'africa_sub_sahariana', 'Rwanda', true, 10),
  ('senegal', 'africa_sub_sahariana', 'Senegal', true, 11),
  ('sudafrica', 'africa_sub_sahariana', 'Sudafrica', true, 12),
  ('tanzania', 'africa_sub_sahariana', 'Tanzania', true, 13),
  ('uganda', 'africa_sub_sahariana', 'Uganda', true, 14),
  ('zimbabwe', 'africa_sub_sahariana', 'Zimbabwe', true, 15),
  ('madagascar', 'isole_delloceano_indiano', 'Madagascar', true, 1),
  ('mauritius', 'isole_delloceano_indiano', 'Mauritius', true, 2),
  ('riunione', 'isole_delloceano_indiano', 'Riunione', true, 3),
  ('seychelles', 'isole_delloceano_indiano', 'Seychelles', true, 4),
  ('algeria', 'nord_africa', 'Algeria', true, 1),
  ('egitto', 'nord_africa', 'Egitto', true, 2),
  ('libia', 'nord_africa', 'Libia', true, 3),
  ('marocco', 'nord_africa', 'Marocco', true, 4),
  ('tunisia', 'nord_africa', 'Tunisia', true, 5),
  ('bhutan', 'asia_centrale_e_subcontinente_indiano', 'Bhutan', true, 1),
  ('india', 'asia_centrale_e_subcontinente_indiano', 'India', true, 2),
  ('kazakistan', 'asia_centrale_e_subcontinente_indiano', 'Kazakistan', true, 3),
  ('kirghizistan', 'asia_centrale_e_subcontinente_indiano', 'Kirghizistan', true, 4),
  ('maldive', 'asia_centrale_e_subcontinente_indiano', 'Maldive', true, 5),
  ('nepal', 'asia_centrale_e_subcontinente_indiano', 'Nepal', true, 6),
  ('sri_lanka', 'asia_centrale_e_subcontinente_indiano', 'Sri Lanka', true, 7),
  ('uzbekistan', 'asia_centrale_e_subcontinente_indiano', 'Uzbekistan', true, 8),
  ('cambogia', 'asia_orientale_e_sud_est_asiatico', 'Cambogia', true, 1),
  ('cina', 'asia_orientale_e_sud_est_asiatico', 'Cina', true, 2),
  ('corea_del_sud', 'asia_orientale_e_sud_est_asiatico', 'Corea del Sud', true, 3),
  ('filippine', 'asia_orientale_e_sud_est_asiatico', 'Filippine', true, 4),
  ('giappone', 'asia_orientale_e_sud_est_asiatico', 'Giappone', true, 5),
  ('indonesia', 'asia_orientale_e_sud_est_asiatico', 'Indonesia', true, 6),
  ('laos', 'asia_orientale_e_sud_est_asiatico', 'Laos', true, 7),
  ('malesia', 'asia_orientale_e_sud_est_asiatico', 'Malesia', true, 8),
  ('mongolia', 'asia_orientale_e_sud_est_asiatico', 'Mongolia', true, 9),
  ('myanmar', 'asia_orientale_e_sud_est_asiatico', 'Myanmar', true, 10),
  ('singapore', 'asia_orientale_e_sud_est_asiatico', 'Singapore', true, 11),
  ('taiwan', 'asia_orientale_e_sud_est_asiatico', 'Taiwan', true, 12),
  ('thailandia', 'asia_orientale_e_sud_est_asiatico', 'Thailandia', true, 13),
  ('vietnam', 'asia_orientale_e_sud_est_asiatico', 'Vietnam', true, 14),
  ('arabia_saudita', 'medio_oriente', 'Arabia Saudita', true, 1),
  ('emirati_arabi_uniti', 'medio_oriente', 'Emirati Arabi Uniti', true, 2),
  ('giordania', 'medio_oriente', 'Giordania', true, 3),
  ('iran', 'medio_oriente', 'Iran', true, 4),
  ('israele', 'medio_oriente', 'Israele', true, 5),
  ('libano', 'medio_oriente', 'Libano', true, 6),
  ('oman', 'medio_oriente', 'Oman', true, 7),
  ('qatar', 'medio_oriente', 'Qatar', true, 8),
  ('belize', 'centro_america_e_caraibi', 'Belize', true, 1),
  ('costa_rica', 'centro_america_e_caraibi', 'Costa Rica', true, 2),
  ('cuba', 'centro_america_e_caraibi', 'Cuba', true, 3),
  ('giamaica', 'centro_america_e_caraibi', 'Giamaica', true, 4),
  ('guatemala', 'centro_america_e_caraibi', 'Guatemala', true, 5),
  ('honduras', 'centro_america_e_caraibi', 'Honduras', true, 6),
  ('messico', 'centro_america_e_caraibi', 'Messico', true, 7),
  ('nicaragua', 'centro_america_e_caraibi', 'Nicaragua', true, 8),
  ('panama', 'centro_america_e_caraibi', 'Panama', true, 9),
  ('repubblica_dominicana', 'centro_america_e_caraibi', 'Repubblica Dominicana', true, 10),
  ('canada', 'nord_america', 'Canada', true, 1),
  ('stati_uniti', 'nord_america', 'Stati Uniti', true, 2),
  ('argentina', 'sud_america', 'Argentina', true, 1),
  ('bolivia', 'sud_america', 'Bolivia', true, 2),
  ('brasile', 'sud_america', 'Brasile', true, 3),
  ('cile', 'sud_america', 'Cile', true, 4),
  ('colombia', 'sud_america', 'Colombia', true, 5),
  ('ecuador', 'sud_america', 'Ecuador', true, 6),
  ('paraguay', 'sud_america', 'Paraguay', true, 7),
  ('peru', 'sud_america', 'Perù', true, 8),
  ('uruguay', 'sud_america', 'Uruguay', true, 9),
  ('venezuela', 'sud_america', 'Venezuela', true, 10),
  ('australia', 'oceania', 'Australia', true, 1),
  ('fiji', 'oceania', 'Fiji', true, 2),
  ('isole_cook', 'oceania', 'Isole Cook', true, 3),
  ('nuova_zelanda', 'oceania', 'Nuova Zelanda', true, 4),
  ('polinesia_francese', 'oceania', 'Polinesia Francese', true, 5),
  ('samoa', 'oceania', 'Samoa', true, 6),
  ('tonga', 'oceania', 'Tonga', true, 7),
  ('antartide', 'antartide', 'Antartide', true, 1)
on conflict (code) do update set
  macro_area_code = excluded.macro_area_code, name_it = excluded.name_it,
  is_selectable = excluded.is_selectable, sort_order = excluded.sort_order;

insert into geo_regions (country_code, slug, name_it, kind, is_selectable) values
  ('armenia', 'armenia', 'Armenia', 'foreign_region', false),
  ('azerbaijan', 'azerbaijan', 'Azerbaijan', 'foreign_region', false),
  ('bielorussia', 'bielorussia', 'Bielorussia', 'foreign_region', false),
  ('georgia', 'georgia', 'Georgia', 'foreign_region', false),
  ('moldavia', 'moldavia', 'Moldavia', 'foreign_region', false),
  ('russia', 'russia_europea', 'Russia Europea', 'foreign_region', false),
  ('russia', 'siberia_e_estremo_oriente', 'Siberia e Estremo Oriente', 'foreign_region', false),
  ('ucraina', 'ucraina', 'Ucraina', 'foreign_region', false),
  ('austria', 'vienna', 'Vienna', 'foreign_region', false),
  ('austria', 'tirolo', 'Tirolo', 'foreign_region', false),
  ('austria', 'salisburghese', 'Salisburghese', 'foreign_region', false),
  ('belgio', 'fiandre', 'Fiandre', 'foreign_region', false),
  ('belgio', 'vallonia', 'Vallonia', 'foreign_region', false),
  ('belgio', 'bruxelles', 'Bruxelles', 'foreign_region', false),
  ('danimarca', 'selandia', 'Selandia', 'foreign_region', false),
  ('danimarca', 'jutland', 'Jutland', 'foreign_region', false),
  ('estonia', 'estonia', 'Estonia', 'foreign_region', false),
  ('finlandia', 'finlandia_meridionale', 'Finlandia Meridionale', 'foreign_region', false),
  ('finlandia', 'lapponia_finlandese', 'Lapponia Finlandese', 'foreign_region', false),
  ('francia', 'île_de_france', 'Île-de-France', 'foreign_region', false),
  ('francia', 'provenza_costa_azzurra', 'Provenza-Costa Azzurra', 'foreign_region', false),
  ('francia', 'normandia', 'Normandia', 'foreign_region', false),
  ('francia', 'bretagna', 'Bretagna', 'foreign_region', false),
  ('francia', 'alvernia_rodano_alpi', 'Alvernia-Rodano-Alpi', 'foreign_region', false),
  ('francia', 'nuova_aquitania', 'Nuova Aquitania', 'foreign_region', false),
  ('germania', 'baviera', 'Baviera', 'foreign_region', false),
  ('germania', 'berlino', 'Berlino', 'foreign_region', false),
  ('germania', 'renania_settentrionale_vestfalia', 'Renania Settentrionale-Vestfalia', 'foreign_region', false),
  ('germania', 'amburgo', 'Amburgo', 'foreign_region', false),
  ('germania', 'sassonia', 'Sassonia', 'foreign_region', false),
  ('irlanda', 'leinster', 'Leinster', 'foreign_region', false),
  ('irlanda', 'munster', 'Munster', 'foreign_region', false),
  ('irlanda', 'connacht', 'Connacht', 'foreign_region', false),
  ('islanda', 'reykjavik_e_sud', 'Reykjavik e Sud', 'foreign_region', false),
  ('islanda', 'nord_e_ovest', 'Nord e Ovest', 'foreign_region', false),
  ('lettonia', 'lettonia', 'Lettonia', 'foreign_region', false),
  ('lituania', 'lituania', 'Lituania', 'foreign_region', false),
  ('lussemburgo', 'lussemburgo', 'Lussemburgo', 'foreign_region', false),
  ('norvegia', 'norvegia_meridionale', 'Norvegia Meridionale', 'foreign_region', false),
  ('norvegia', 'fiordi_occidentali', 'Fiordi Occidentali', 'foreign_region', false),
  ('norvegia', 'norvegia_settentrionale', 'Norvegia Settentrionale', 'foreign_region', false),
  ('paesi_bassi', 'olanda_settentrionale', 'Olanda Settentrionale', 'foreign_region', false),
  ('paesi_bassi', 'olanda_meridionale', 'Olanda Meridionale', 'foreign_region', false),
  ('paesi_bassi', 'utrecht', 'Utrecht', 'foreign_region', false),
  ('polonia', 'masovia', 'Masovia', 'foreign_region', false),
  ('polonia', 'piccola_polonia', 'Piccola Polonia', 'foreign_region', false),
  ('polonia', 'pomerania', 'Pomerania', 'foreign_region', false),
  ('regno_unito', 'inghilterra', 'Inghilterra', 'foreign_region', false),
  ('regno_unito', 'scozia', 'Scozia', 'foreign_region', false),
  ('regno_unito', 'galles', 'Galles', 'foreign_region', false),
  ('regno_unito', 'irlanda_del_nord', 'Irlanda del Nord', 'foreign_region', false),
  ('repubblica_ceca', 'boemia', 'Boemia', 'foreign_region', false),
  ('repubblica_ceca', 'moravia', 'Moravia', 'foreign_region', false),
  ('slovacchia', 'bratislava', 'Bratislava', 'foreign_region', false),
  ('slovacchia', 'alti_tatra', 'Alti Tatra', 'foreign_region', false),
  ('svezia', 'stoccolma', 'Stoccolma', 'foreign_region', false),
  ('svezia', 'lapponia_svedese', 'Lapponia Svedese', 'foreign_region', false),
  ('svezia', 'götaland', 'Götaland', 'foreign_region', false),
  ('svizzera', 'romandia', 'Romandia', 'foreign_region', false),
  ('svizzera', 'svizzera_tedesca', 'Svizzera Tedesca', 'foreign_region', false),
  ('svizzera', 'ticino', 'Ticino', 'foreign_region', false),
  ('svizzera', 'grigioni', 'Grigioni', 'foreign_region', false),
  ('ungheria', 'budapest', 'Budapest', 'foreign_region', false),
  ('ungheria', 'transdanubio', 'Transdanubio', 'foreign_region', false),
  ('albania', 'albania', 'Albania', 'foreign_region', false),
  ('bosnia_ed_erzegovina', 'bosnia_ed_erzegovina', 'Bosnia ed Erzegovina', 'foreign_region', false),
  ('bulgaria', 'bulgaria', 'Bulgaria', 'foreign_region', false),
  ('cipro', 'cipro', 'Cipro', 'foreign_region', false),
  ('croazia', 'dalmazia', 'Dalmazia', 'foreign_region', false),
  ('croazia', 'istria', 'Istria', 'foreign_region', false),
  ('croazia', 'zagabria_e_continentale', 'Zagabria e Continentale', 'foreign_region', false),
  ('grecia', 'attica', 'Attica', 'foreign_region', false),
  ('grecia', 'isole_cicladi', 'Isole Cicladi', 'foreign_region', false),
  ('grecia', 'creta', 'Creta', 'foreign_region', false),
  ('grecia', 'isole_ionie', 'Isole Ionie', 'foreign_region', false),
  ('grecia', 'peloponneso', 'Peloponneso', 'foreign_region', false),
  ('italia', 'abruzzo', 'Abruzzo', 'italian_region', true),
  ('italia', 'basilicata', 'Basilicata', 'italian_region', true),
  ('italia', 'calabria', 'Calabria', 'italian_region', true),
  ('italia', 'campania', 'Campania', 'italian_region', true),
  ('italia', 'emilia_romagna', 'Emilia-Romagna', 'italian_region', true),
  ('italia', 'friuli_venezia_giulia', 'Friuli-Venezia Giulia', 'italian_region', true),
  ('italia', 'lazio', 'Lazio', 'italian_region', true),
  ('italia', 'liguria', 'Liguria', 'italian_region', true),
  ('italia', 'lombardia', 'Lombardia', 'italian_region', true),
  ('italia', 'marche', 'Marche', 'italian_region', true),
  ('italia', 'molise', 'Molise', 'italian_region', true),
  ('italia', 'piemonte', 'Piemonte', 'italian_region', true),
  ('italia', 'puglia', 'Puglia', 'italian_region', true),
  ('italia', 'sardegna', 'Sardegna', 'italian_region', true),
  ('italia', 'sicilia', 'Sicilia', 'italian_region', true),
  ('italia', 'toscana', 'Toscana', 'italian_region', true),
  ('italia', 'trentino_alto_adige', 'Trentino-Alto Adige', 'italian_region', true),
  ('italia', 'umbria', 'Umbria', 'italian_region', true),
  ('italia', 'valle_daosta', 'Valle d''Aosta', 'italian_region', true),
  ('italia', 'veneto', 'Veneto', 'italian_region', true),
  ('kosovo', 'kosovo', 'Kosovo', 'foreign_region', false),
  ('macedonia_del_nord', 'macedonia_del_nord', 'Macedonia del Nord', 'foreign_region', false),
  ('malta', 'malta', 'Malta', 'foreign_region', false),
  ('malta', 'gozo', 'Gozo', 'foreign_region', false),
  ('montenegro', 'montenegro', 'Montenegro', 'foreign_region', false),
  ('portogallo', 'lisbona_e_centro', 'Lisbona e Centro', 'foreign_region', false),
  ('portogallo', 'porto_e_nord', 'Porto e Nord', 'foreign_region', false),
  ('portogallo', 'algarve', 'Algarve', 'foreign_region', false),
  ('portogallo', 'madeira', 'Madeira', 'foreign_region', false),
  ('portogallo', 'azzorre', 'Azzorre', 'foreign_region', false),
  ('romania', 'transilvania', 'Transilvania', 'foreign_region', false),
  ('romania', 'bucarest_e_sud', 'Bucarest e Sud', 'foreign_region', false),
  ('romania', 'moldavia_rumena', 'Moldavia rumena', 'foreign_region', false),
  ('serbia', 'serbia', 'Serbia', 'foreign_region', false),
  ('slovenia', 'slovenia', 'Slovenia', 'foreign_region', false),
  ('spagna', 'catalogna', 'Catalogna', 'foreign_region', false),
  ('spagna', 'andalusia', 'Andalusia', 'foreign_region', false),
  ('spagna', 'madrid', 'Madrid', 'foreign_region', false),
  ('spagna', 'paesi_baschi', 'Paesi Baschi', 'foreign_region', false),
  ('spagna', 'isole_baleari', 'Isole Baleari', 'foreign_region', false),
  ('spagna', 'isole_canarie', 'Isole Canarie', 'foreign_region', false),
  ('spagna', 'galizia', 'Galizia', 'foreign_region', false),
  ('turchia', 'istanbul_e_marmara', 'Istanbul e Marmara', 'foreign_region', false),
  ('turchia', 'egeo', 'Egeo', 'foreign_region', false),
  ('turchia', 'mediterraneo', 'Mediterraneo', 'foreign_region', false),
  ('turchia', 'cappadocia_e_anatolia_centrale', 'Cappadocia e Anatolia Centrale', 'foreign_region', false),
  ('botswana', 'botswana', 'Botswana', 'foreign_region', false),
  ('capo_verde', 'capo_verde', 'Capo Verde', 'foreign_region', false),
  ('costa_davorio', 'costa_davorio', 'Costa d''Avorio', 'foreign_region', false),
  ('etiopia', 'etiopia', 'Etiopia', 'foreign_region', false),
  ('ghana', 'ghana', 'Ghana', 'foreign_region', false),
  ('kenya', 'costa', 'Costa', 'foreign_region', false),
  ('kenya', 'safari_e_interno', 'Safari e Interno', 'foreign_region', false),
  ('mozambico', 'mozambico', 'Mozambico', 'foreign_region', false),
  ('namibia', 'namibia', 'Namibia', 'foreign_region', false),
  ('nigeria', 'nigeria', 'Nigeria', 'foreign_region', false),
  ('rwanda', 'rwanda', 'Rwanda', 'foreign_region', false),
  ('senegal', 'senegal', 'Senegal', 'foreign_region', false),
  ('sudafrica', 'capo', 'Capo', 'foreign_region', false),
  ('sudafrica', 'nord_est', 'Nord-Est', 'foreign_region', false),
  ('sudafrica', 'kwazulu_natal', 'KwaZulu-Natal', 'foreign_region', false),
  ('tanzania', 'continentale', 'Continentale', 'foreign_region', false),
  ('tanzania', 'zanzibar', 'Zanzibar', 'foreign_region', false),
  ('uganda', 'uganda', 'Uganda', 'foreign_region', false),
  ('zimbabwe', 'zimbabwe', 'Zimbabwe', 'foreign_region', false),
  ('madagascar', 'madagascar', 'Madagascar', 'foreign_region', false),
  ('mauritius', 'mauritius', 'Mauritius', 'foreign_region', false),
  ('riunione', 'riunione', 'Riunione', 'foreign_region', false),
  ('seychelles', 'seychelles', 'Seychelles', 'foreign_region', false),
  ('algeria', 'algeria', 'Algeria', 'foreign_region', false),
  ('egitto', 'cairo_e_nilo', 'Cairo e Nilo', 'foreign_region', false),
  ('egitto', 'mar_rosso', 'Mar Rosso', 'foreign_region', false),
  ('libia', 'libia', 'Libia', 'foreign_region', false),
  ('marocco', 'marocco_imperiale', 'Marocco Imperiale', 'foreign_region', false),
  ('marocco', 'sahara_e_sud', 'Sahara e Sud', 'foreign_region', false),
  ('marocco', 'costa_atlantica', 'Costa Atlantica', 'foreign_region', false),
  ('tunisia', 'tunisia', 'Tunisia', 'foreign_region', false),
  ('bhutan', 'bhutan', 'Bhutan', 'foreign_region', false),
  ('india', 'india_del_nord', 'India del Nord', 'foreign_region', false),
  ('india', 'rajasthan', 'Rajasthan', 'foreign_region', false),
  ('india', 'india_del_sud', 'India del Sud', 'foreign_region', false),
  ('india', 'goa_e_kerala', 'Goa e Kerala', 'foreign_region', false),
  ('kazakistan', 'kazakistan', 'Kazakistan', 'foreign_region', false),
  ('kirghizistan', 'kirghizistan', 'Kirghizistan', 'foreign_region', false),
  ('maldive', 'maldive', 'Maldive', 'foreign_region', false),
  ('nepal', 'nepal', 'Nepal', 'foreign_region', false),
  ('sri_lanka', 'sri_lanka', 'Sri Lanka', 'foreign_region', false),
  ('uzbekistan', 'uzbekistan', 'Uzbekistan', 'foreign_region', false),
  ('cambogia', 'cambogia', 'Cambogia', 'foreign_region', false),
  ('cina', 'cina_orientale', 'Cina Orientale', 'foreign_region', false),
  ('cina', 'cina_del_sud', 'Cina del Sud', 'foreign_region', false),
  ('cina', 'cina_dellovest', 'Cina dell''Ovest', 'foreign_region', false),
  ('corea_del_sud', 'corea_del_sud', 'Corea del Sud', 'foreign_region', false),
  ('filippine', 'filippine', 'Filippine', 'foreign_region', false),
  ('giappone', 'honshu', 'Honshu', 'foreign_region', false),
  ('giappone', 'hokkaido', 'Hokkaido', 'foreign_region', false),
  ('giappone', 'kyushu_e_okinawa', 'Kyushu e Okinawa', 'foreign_region', false),
  ('indonesia', 'bali_e_nusa_tenggara', 'Bali e Nusa Tenggara', 'foreign_region', false),
  ('indonesia', 'giava', 'Giava', 'foreign_region', false),
  ('indonesia', 'sumatra_e_borneo', 'Sumatra e Borneo', 'foreign_region', false),
  ('indonesia', 'sulawesi_e_papua', 'Sulawesi e Papua', 'foreign_region', false),
  ('laos', 'laos', 'Laos', 'foreign_region', false),
  ('malesia', 'malesia_peninsulare', 'Malesia Peninsulare', 'foreign_region', false),
  ('malesia', 'borneo_malese', 'Borneo Malese', 'foreign_region', false),
  ('mongolia', 'mongolia', 'Mongolia', 'foreign_region', false),
  ('myanmar', 'myanmar', 'Myanmar', 'foreign_region', false),
  ('singapore', 'singapore', 'Singapore', 'foreign_region', false),
  ('taiwan', 'taiwan', 'Taiwan', 'foreign_region', false),
  ('thailandia', 'thailandia_del_nord', 'Thailandia del Nord', 'foreign_region', false),
  ('thailandia', 'thailandia_centrale', 'Thailandia Centrale', 'foreign_region', false),
  ('thailandia', 'thailandia_del_sud', 'Thailandia del Sud', 'foreign_region', false),
  ('vietnam', 'vietnam_del_nord', 'Vietnam del Nord', 'foreign_region', false),
  ('vietnam', 'vietnam_centrale', 'Vietnam Centrale', 'foreign_region', false),
  ('vietnam', 'vietnam_del_sud', 'Vietnam del Sud', 'foreign_region', false),
  ('arabia_saudita', 'arabia_saudita', 'Arabia Saudita', 'foreign_region', false),
  ('emirati_arabi_uniti', 'emirati_arabi_uniti', 'Emirati Arabi Uniti', 'foreign_region', false),
  ('giordania', 'giordania', 'Giordania', 'foreign_region', false),
  ('iran', 'iran', 'Iran', 'foreign_region', false),
  ('israele', 'israele', 'Israele', 'foreign_region', false),
  ('libano', 'libano', 'Libano', 'foreign_region', false),
  ('oman', 'oman', 'Oman', 'foreign_region', false),
  ('qatar', 'qatar', 'Qatar', 'foreign_region', false),
  ('belize', 'belize', 'Belize', 'foreign_region', false),
  ('costa_rica', 'costa_rica', 'Costa Rica', 'foreign_region', false),
  ('cuba', 'cuba', 'Cuba', 'foreign_region', false),
  ('giamaica', 'giamaica', 'Giamaica', 'foreign_region', false),
  ('guatemala', 'guatemala', 'Guatemala', 'foreign_region', false),
  ('honduras', 'honduras', 'Honduras', 'foreign_region', false),
  ('messico', 'yucatán_e_caraibi', 'Yucatán e Caraibi', 'foreign_region', false),
  ('messico', 'messico_centrale', 'Messico Centrale', 'foreign_region', false),
  ('messico', 'bassa_california', 'Bassa California', 'foreign_region', false),
  ('nicaragua', 'nicaragua', 'Nicaragua', 'foreign_region', false),
  ('panama', 'panama', 'Panama', 'foreign_region', false),
  ('repubblica_dominicana', 'repubblica_dominicana', 'Repubblica Dominicana', 'foreign_region', false),
  ('canada', 'canada_orientale', 'Canada Orientale', 'foreign_region', false),
  ('canada', 'canada_occidentale', 'Canada Occidentale', 'foreign_region', false),
  ('stati_uniti', 'costa_est', 'Costa Est', 'foreign_region', false),
  ('stati_uniti', 'costa_ovest', 'Costa Ovest', 'foreign_region', false),
  ('stati_uniti', 'sud', 'Sud', 'foreign_region', false),
  ('stati_uniti', 'midwest_e_montagne', 'Midwest e Montagne', 'foreign_region', false),
  ('stati_uniti', 'hawaii_e_alaska', 'Hawaii e Alaska', 'foreign_region', false),
  ('argentina', 'argentina_del_nord', 'Argentina del Nord', 'foreign_region', false),
  ('argentina', 'patagonia_argentina', 'Patagonia Argentina', 'foreign_region', false),
  ('bolivia', 'bolivia', 'Bolivia', 'foreign_region', false),
  ('brasile', 'sud_est', 'Sud-Est', 'foreign_region', false),
  ('brasile', 'nord_est', 'Nord-Est', 'foreign_region', false),
  ('brasile', 'amazzonia_e_pantanal', 'Amazzonia e Pantanal', 'foreign_region', false),
  ('cile', 'cile_del_nord_e_centro', 'Cile del Nord e Centro', 'foreign_region', false),
  ('cile', 'patagonia_cilena', 'Patagonia Cilena', 'foreign_region', false),
  ('cile', 'isola_di_pasqua', 'Isola di Pasqua', 'foreign_region', false),
  ('colombia', 'colombia', 'Colombia', 'foreign_region', false),
  ('ecuador', 'ecuador_continentale', 'Ecuador continentale', 'foreign_region', false),
  ('ecuador', 'galápagos', 'Galápagos', 'foreign_region', false),
  ('paraguay', 'paraguay', 'Paraguay', 'foreign_region', false),
  ('peru', 'peru', 'Perù', 'foreign_region', false),
  ('uruguay', 'uruguay', 'Uruguay', 'foreign_region', false),
  ('venezuela', 'venezuela', 'Venezuela', 'foreign_region', false),
  ('australia', 'australia_orientale', 'Australia Orientale', 'foreign_region', false),
  ('australia', 'australia_centrale_e_ovest', 'Australia Centrale e Ovest', 'foreign_region', false),
  ('australia', 'tasmania', 'Tasmania', 'foreign_region', false),
  ('fiji', 'fiji', 'Fiji', 'foreign_region', false),
  ('isole_cook', 'isole_cook', 'Isole Cook', 'foreign_region', false),
  ('nuova_zelanda', 'isola_del_nord', 'Isola del Nord', 'foreign_region', false),
  ('nuova_zelanda', 'isola_del_sud', 'Isola del Sud', 'foreign_region', false),
  ('polinesia_francese', 'polinesia_francese', 'Polinesia Francese', 'foreign_region', false),
  ('samoa', 'samoa', 'Samoa', 'foreign_region', false),
  ('tonga', 'tonga', 'Tonga', 'foreign_region', false),
  ('antartide', 'antartide', 'Antartide', 'foreign_region', false)
on conflict (country_code, slug) do update set
  name_it = excluded.name_it, kind = excluded.kind, is_selectable = excluded.is_selectable;

-- Le città si agganciano alla regione risolvendo (stato, slug regione). Stanno
-- in una tabella temporanea perché servono tre volte: per la guardia, per
-- l'inserimento e per la potatura.
-- Il drop in testa rende il seed rilanciabile anche dopo un giro fermato a metà.
drop table if exists geo_citta_attese;
create temp table geo_citta_attese (
  country_code text, region_slug text, city_slug text, city_name text, is_selectable boolean
);
insert into geo_citta_attese values
  ('armenia', 'armenia', 'yerevan', 'Yerevan', false),
  ('azerbaijan', 'azerbaijan', 'baku', 'Baku', false),
  ('bielorussia', 'bielorussia', 'minsk', 'Minsk', false),
  ('georgia', 'georgia', 'tbilisi', 'Tbilisi', false),
  ('moldavia', 'moldavia', 'chișinău', 'Chișinău', false),
  ('russia', 'russia_europea', 'mosca', 'Mosca', false),
  ('russia', 'russia_europea', 'san_pietroburgo', 'San Pietroburgo', false),
  ('ucraina', 'ucraina', 'kiev', 'Kiev', false),
  ('austria', 'vienna', 'vienna', 'Vienna', false),
  ('belgio', 'bruxelles', 'bruxelles', 'Bruxelles', false),
  ('danimarca', 'selandia', 'copenaghen', 'Copenaghen', false),
  ('estonia', 'estonia', 'tallinn', 'Tallinn', false),
  ('finlandia', 'finlandia_meridionale', 'helsinki', 'Helsinki', false),
  ('francia', 'île_de_france', 'parigi', 'Parigi', false),
  ('francia', 'provenza_costa_azzurra', 'nizza', 'Nizza', false),
  ('germania', 'baviera', 'monaco', 'Monaco', false),
  ('germania', 'berlino', 'berlino', 'Berlino', false),
  ('irlanda', 'leinster', 'dublino', 'Dublino', false),
  ('islanda', 'reykjavik_e_sud', 'reykjavik', 'Reykjavik', false),
  ('lettonia', 'lettonia', 'riga', 'Riga', false),
  ('lituania', 'lituania', 'vilnius', 'Vilnius', false),
  ('lussemburgo', 'lussemburgo', 'lussemburgo_citta', 'Lussemburgo Città', false),
  ('norvegia', 'norvegia_meridionale', 'oslo', 'Oslo', false),
  ('norvegia', 'norvegia_meridionale', 'bergen', 'Bergen', false),
  ('paesi_bassi', 'olanda_settentrionale', 'amsterdam', 'Amsterdam', false),
  ('polonia', 'masovia', 'varsavia', 'Varsavia', false),
  ('polonia', 'piccola_polonia', 'cracovia', 'Cracovia', false),
  ('regno_unito', 'inghilterra', 'londra', 'Londra', false),
  ('regno_unito', 'scozia', 'edimburgo', 'Edimburgo', false),
  ('repubblica_ceca', 'boemia', 'praga', 'Praga', false),
  ('slovacchia', 'bratislava', 'bratislava', 'Bratislava', false),
  ('svezia', 'stoccolma', 'stoccolma', 'Stoccolma', false),
  ('svizzera', 'romandia', 'ginevra', 'Ginevra', false),
  ('svizzera', 'svizzera_tedesca', 'zurigo', 'Zurigo', false),
  ('ungheria', 'budapest', 'budapest', 'Budapest', false),
  ('albania', 'albania', 'tirana', 'Tirana', false),
  ('bosnia_ed_erzegovina', 'bosnia_ed_erzegovina', 'sarajevo', 'Sarajevo', false),
  ('bulgaria', 'bulgaria', 'sofia', 'Sofia', false),
  ('cipro', 'cipro', 'nicosia', 'Nicosia', false),
  ('croazia', 'dalmazia', 'dubrovnik', 'Dubrovnik', false),
  ('grecia', 'attica', 'atene', 'Atene', false),
  ('grecia', 'isole_cicladi', 'santorini', 'Santorini', false),
  ('italia', 'abruzzo', 'laquila', 'L''Aquila', false),
  ('italia', 'basilicata', 'matera', 'Matera', false),
  ('italia', 'calabria', 'reggio_calabria', 'Reggio Calabria', false),
  ('italia', 'campania', 'napoli', 'Napoli', false),
  ('italia', 'emilia_romagna', 'bologna', 'Bologna', false),
  ('italia', 'friuli_venezia_giulia', 'trieste', 'Trieste', false),
  ('italia', 'lazio', 'roma', 'Roma', false),
  ('italia', 'liguria', 'genova', 'Genova', false),
  ('italia', 'lombardia', 'milano', 'Milano', false),
  ('italia', 'marche', 'ancona', 'Ancona', false),
  ('italia', 'molise', 'campobasso', 'Campobasso', false),
  ('italia', 'piemonte', 'torino', 'Torino', false),
  ('italia', 'puglia', 'bari', 'Bari', false),
  ('italia', 'sardegna', 'cagliari', 'Cagliari', false),
  ('italia', 'sicilia', 'palermo', 'Palermo', false),
  ('italia', 'toscana', 'firenze', 'Firenze', false),
  ('italia', 'trentino_alto_adige', 'trento', 'Trento', false),
  ('italia', 'umbria', 'perugia', 'Perugia', false),
  ('italia', 'valle_daosta', 'aosta', 'Aosta', false),
  ('italia', 'veneto', 'venezia', 'Venezia', false),
  ('kosovo', 'kosovo', 'pristina', 'Pristina', false),
  ('macedonia_del_nord', 'macedonia_del_nord', 'skopje', 'Skopje', false),
  ('malta', 'malta', 'la_valletta', 'La Valletta', false),
  ('montenegro', 'montenegro', 'kotor', 'Kotor', false),
  ('portogallo', 'lisbona_e_centro', 'lisbona', 'Lisbona', false),
  ('portogallo', 'porto_e_nord', 'porto', 'Porto', false),
  ('romania', 'bucarest_e_sud', 'bucarest', 'Bucarest', false),
  ('serbia', 'serbia', 'belgrado', 'Belgrado', false),
  ('slovenia', 'slovenia', 'lubiana', 'Lubiana', false),
  ('spagna', 'catalogna', 'barcellona', 'Barcellona', false),
  ('spagna', 'madrid', 'madrid', 'Madrid', false),
  ('turchia', 'istanbul_e_marmara', 'istanbul', 'Istanbul', false),
  ('botswana', 'botswana', 'okavango_delta', 'Okavango Delta', false),
  ('capo_verde', 'capo_verde', 'praia', 'Praia', false),
  ('costa_davorio', 'costa_davorio', 'abidjan', 'Abidjan', false),
  ('etiopia', 'etiopia', 'addis_abeba', 'Addis Abeba', false),
  ('ghana', 'ghana', 'accra', 'Accra', false),
  ('kenya', 'safari_e_interno', 'nairobi', 'Nairobi', false),
  ('mozambico', 'mozambico', 'maputo', 'Maputo', false),
  ('namibia', 'namibia', 'windhoek', 'Windhoek', false),
  ('nigeria', 'nigeria', 'lagos', 'Lagos', false),
  ('rwanda', 'rwanda', 'kigali', 'Kigali', false),
  ('senegal', 'senegal', 'dakar', 'Dakar', false),
  ('sudafrica', 'capo', 'citta_del_capo', 'Città del Capo', false),
  ('sudafrica', 'nord_est', 'johannesburg', 'Johannesburg', false),
  ('tanzania', 'continentale', 'dar_es_salaam', 'Dar es Salaam', false),
  ('tanzania', 'zanzibar', 'stone_town', 'Stone Town', false),
  ('uganda', 'uganda', 'kampala', 'Kampala', false),
  ('zimbabwe', 'zimbabwe', 'harare', 'Harare', false),
  ('zimbabwe', 'zimbabwe', 'victoria_falls', 'Victoria Falls', false),
  ('madagascar', 'madagascar', 'antananarivo', 'Antananarivo', false),
  ('mauritius', 'mauritius', 'port_louis', 'Port Louis', false),
  ('riunione', 'riunione', 'saint_denis', 'Saint-Denis', false),
  ('seychelles', 'seychelles', 'victoria', 'Victoria', false),
  ('algeria', 'algeria', 'algeri', 'Algeri', false),
  ('egitto', 'cairo_e_nilo', 'il_cairo', 'Il Cairo', false),
  ('egitto', 'cairo_e_nilo', 'luxor', 'Luxor', false),
  ('libia', 'libia', 'tripoli', 'Tripoli', false),
  ('marocco', 'marocco_imperiale', 'marrakech', 'Marrakech', false),
  ('marocco', 'marocco_imperiale', 'casablanca', 'Casablanca', false),
  ('tunisia', 'tunisia', 'tunisi', 'Tunisi', false),
  ('bhutan', 'bhutan', 'thimphu', 'Thimphu', false),
  ('india', 'india_del_nord', 'delhi', 'Delhi', false),
  ('india', 'india_del_nord', 'agra', 'Agra', false),
  ('kazakistan', 'kazakistan', 'almaty', 'Almaty', false),
  ('kirghizistan', 'kirghizistan', 'bishkek', 'Bishkek', false),
  ('maldive', 'maldive', 'male', 'Malé', false),
  ('nepal', 'nepal', 'kathmandu', 'Kathmandu', false),
  ('sri_lanka', 'sri_lanka', 'colombo', 'Colombo', false),
  ('uzbekistan', 'uzbekistan', 'samarcanda', 'Samarcanda', false),
  ('cambogia', 'cambogia', 'phnom_penh', 'Phnom Penh', false),
  ('cambogia', 'cambogia', 'siem_reap', 'Siem Reap', false),
  ('cina', 'cina_orientale', 'pechino', 'Pechino', false),
  ('cina', 'cina_orientale', 'shanghai', 'Shanghai', false),
  ('cina', 'cina_del_sud', 'hong_kong', 'Hong Kong', false),
  ('corea_del_sud', 'corea_del_sud', 'seoul', 'Seoul', false),
  ('filippine', 'filippine', 'manila', 'Manila', false),
  ('giappone', 'honshu', 'tokyo', 'Tokyo', false),
  ('giappone', 'honshu', 'kyoto', 'Kyoto', false),
  ('giappone', 'honshu', 'osaka', 'Osaka', false),
  ('indonesia', 'bali_e_nusa_tenggara', 'ubud', 'Ubud', false),
  ('indonesia', 'giava', 'jakarta', 'Jakarta', false),
  ('laos', 'laos', 'luang_prabang', 'Luang Prabang', false),
  ('malesia', 'malesia_peninsulare', 'kuala_lumpur', 'Kuala Lumpur', false),
  ('mongolia', 'mongolia', 'ulaanbaatar', 'Ulaanbaatar', false),
  ('myanmar', 'myanmar', 'yangon', 'Yangon', false),
  ('singapore', 'singapore', 'marina_bay', 'Marina Bay', false),
  ('taiwan', 'taiwan', 'taipei', 'Taipei', false),
  ('thailandia', 'thailandia_centrale', 'bangkok', 'Bangkok', false),
  ('thailandia', 'thailandia_del_sud', 'phuket', 'Phuket', false),
  ('vietnam', 'vietnam_del_nord', 'hanoi', 'Hanoi', false),
  ('vietnam', 'vietnam_del_sud', 'ho_chi_minh_city', 'Ho Chi Minh City', false),
  ('arabia_saudita', 'arabia_saudita', 'riad', 'Riad', false),
  ('arabia_saudita', 'arabia_saudita', 'jeddah', 'Jeddah', false),
  ('emirati_arabi_uniti', 'emirati_arabi_uniti', 'dubai', 'Dubai', false),
  ('emirati_arabi_uniti', 'emirati_arabi_uniti', 'abu_dhabi', 'Abu Dhabi', false),
  ('giordania', 'giordania', 'amman', 'Amman', false),
  ('iran', 'iran', 'teheran', 'Teheran', false),
  ('israele', 'israele', 'gerusalemme', 'Gerusalemme', false),
  ('israele', 'israele', 'tel_aviv', 'Tel Aviv', false),
  ('libano', 'libano', 'beirut', 'Beirut', false),
  ('oman', 'oman', 'muscat', 'Muscat', false),
  ('qatar', 'qatar', 'doha', 'Doha', false),
  ('belize', 'belize', 'belize_city', 'Belize City', false),
  ('costa_rica', 'costa_rica', 'san_jose', 'San José', false),
  ('cuba', 'cuba', 'lavana', 'L''Avana', false),
  ('giamaica', 'giamaica', 'kingston', 'Kingston', false),
  ('guatemala', 'guatemala', 'citta_del_guatemala', 'Città del Guatemala', false),
  ('honduras', 'honduras', 'tegucigalpa', 'Tegucigalpa', false),
  ('messico', 'yucatán_e_caraibi', 'cancún', 'Cancún', false),
  ('messico', 'messico_centrale', 'citta_del_messico', 'Città del Messico', false),
  ('nicaragua', 'nicaragua', 'managua', 'Managua', false),
  ('panama', 'panama', 'panama_city', 'Panama City', false),
  ('repubblica_dominicana', 'repubblica_dominicana', 'santo_domingo', 'Santo Domingo', false),
  ('canada', 'canada_orientale', 'toronto', 'Toronto', false),
  ('canada', 'canada_occidentale', 'vancouver', 'Vancouver', false),
  ('stati_uniti', 'costa_est', 'new_york', 'New York', false),
  ('stati_uniti', 'costa_est', 'washington_dc', 'Washington DC', false),
  ('stati_uniti', 'costa_est', 'miami', 'Miami', false),
  ('stati_uniti', 'costa_ovest', 'los_angeles', 'Los Angeles', false),
  ('stati_uniti', 'costa_ovest', 'san_francisco', 'San Francisco', false),
  ('stati_uniti', 'costa_ovest', 'las_vegas', 'Las Vegas', false),
  ('stati_uniti', 'midwest_e_montagne', 'chicago', 'Chicago', false),
  ('stati_uniti', 'hawaii_e_alaska', 'honolulu', 'Honolulu', false),
  ('argentina', 'argentina_del_nord', 'buenos_aires', 'Buenos Aires', false),
  ('bolivia', 'bolivia', 'la_paz', 'La Paz', false),
  ('brasile', 'sud_est', 'rio_de_janeiro', 'Rio de Janeiro', false),
  ('brasile', 'sud_est', 'san_paolo', 'San Paolo', false),
  ('cile', 'cile_del_nord_e_centro', 'santiago', 'Santiago', false),
  ('colombia', 'colombia', 'bogotá', 'Bogotá', false),
  ('colombia', 'colombia', 'cartagena', 'Cartagena', false),
  ('ecuador', 'ecuador_continentale', 'quito', 'Quito', false),
  ('paraguay', 'paraguay', 'asunción', 'Asunción', false),
  ('peru', 'peru', 'lima', 'Lima', false),
  ('peru', 'peru', 'cusco', 'Cusco', false),
  ('uruguay', 'uruguay', 'montevideo', 'Montevideo', false),
  ('venezuela', 'venezuela', 'caracas', 'Caracas', false),
  ('australia', 'australia_orientale', 'sydney', 'Sydney', false),
  ('australia', 'australia_orientale', 'melbourne', 'Melbourne', false),
  ('fiji', 'fiji', 'nadi', 'Nadi', false),
  ('isole_cook', 'isole_cook', 'rarotonga', 'Rarotonga', false),
  ('nuova_zelanda', 'isola_del_nord', 'auckland', 'Auckland', false),
  ('nuova_zelanda', 'isola_del_sud', 'queenstown', 'Queenstown', false),
  ('polinesia_francese', 'polinesia_francese', 'bora_bora', 'Bora Bora', false),
  ('samoa', 'samoa', 'apia', 'Apia', false),
  ('tonga', 'tonga', 'nukualofa', 'Nuku''alofa', false);

-- Guardia: una città senza la sua regione verrebbe scartata dalla join in
-- silenzio. Meglio fermarsi.
do $$
declare v_orfane text;
begin
  select string_agg(v.country_code || '/' || v.region_slug || '/' || v.city_slug, ', ') into v_orfane
    from geo_citta_attese v
   where not exists (select 1 from geo_regions r
                      where r.country_code = v.country_code and r.slug = v.region_slug);
  if v_orfane is not null then
    raise exception 'Città senza regione nel database: %', v_orfane;
  end if;
end $$;

insert into geo_cities (country_code, region_id, slug, name_it, is_selectable)
select v.country_code, r.id, v.city_slug, v.city_name, v.is_selectable
  from geo_citta_attese v
  join geo_regions r on r.country_code = v.country_code and r.slug = v.region_slug
on conflict (region_id, slug) do update set
  name_it = excluded.name_it, is_selectable = excluded.is_selectable;

-- La potatura: le città che il file non ha più se ne vanno. Nessuna chiave
-- esterna punta a geo_cities (verificato il 27 settembre 2026), quindi non
-- trascina niente con sé. Su un database vuoto non fa nulla.
delete from geo_cities c
 where not exists (
   select 1 from geo_citta_attese v
     join geo_regions r on r.country_code = v.country_code and r.slug = v.region_slug
    where r.id = c.region_id and v.city_slug = c.slug);

drop table geo_citta_attese;

commit;
