-- XPETIS · seed 0002 · Tassonomia geografica
--
-- GENERATO da supabase/scripts/genera_geo.mjs a partire da
-- xpetis_destinazioni_v2.json. Non modificare a mano: rigenerare.
-- Attese: 6 continenti, 14 macro-aree, 139 stati, 188 città (nessuna regione, 0057).

-- Regole di selezione dichiarate dalla tassonomia:
--   selezionabili: macro_area, state
--   solo cercabili: continent, city

-- Tutto in una transazione: rigirato sopra dati esistenti, un giro fermato
-- da una guardia non deve lasciare mezza potatura.
begin;

-- Guardia: nel database non ci devono essere continenti, macro-aree o stati
-- che il file non ha. Non si cancellano da qui (uno stato ha dietro
-- td_countries e quiz_responses): si ferma tutto e lo si dice.
do $$
declare v_extra text;
begin
  select string_agg(x, ', ') into v_extra from (
    select 'continente ' || code as x from geo_continents where code <> all (array['europa', 'africa', 'asia', 'americhe', 'oceania', 'antartide']::text[])
    union all select 'macro-area ' || code from geo_macro_areas where code <> all (array['europa_est_e_caucaso', 'europa_nord', 'europa_sud', 'africa_sub_sahariana', 'isole_delloceano_indiano', 'nord_africa', 'asia_centrale_e_subcontinente_indiano', 'asia_orientale_e_sud_est_asiatico', 'medio_oriente', 'centro_america_e_caraibi', 'nord_america', 'sud_america', 'oceania', 'antartide']::text[])
    union all select 'stato ' || code from geo_countries where code <> all (array['armenia', 'azerbaijan', 'bielorussia', 'georgia', 'moldavia', 'russia', 'ucraina', 'austria', 'belgio', 'danimarca', 'estonia', 'finlandia', 'francia', 'germania', 'irlanda', 'islanda', 'lettonia', 'lituania', 'lussemburgo', 'norvegia', 'paesi_bassi', 'polonia', 'regno_unito', 'repubblica_ceca', 'slovacchia', 'svezia', 'svizzera', 'ungheria', 'albania', 'andorra', 'bosnia_ed_erzegovina', 'bulgaria', 'cipro', 'croazia', 'grecia', 'italia', 'kosovo', 'macedonia_del_nord', 'malta', 'montenegro', 'portogallo', 'romania', 'serbia', 'slovenia', 'spagna', 'turchia', 'angola', 'botswana', 'capo_verde', 'costa_davorio', 'eritrea', 'etiopia', 'gambia', 'ghana', 'kenya', 'mozambico', 'namibia', 'nigeria', 'rwanda', 'senegal', 'sudafrica', 'tanzania', 'uganda', 'zimbabwe', 'madagascar', 'mauritius', 'riunione', 'seychelles', 'algeria', 'egitto', 'libia', 'marocco', 'tunisia', 'bangladesh', 'bhutan', 'india', 'kazakistan', 'kirghizistan', 'maldive', 'nepal', 'sri_lanka', 'uzbekistan', 'cambogia', 'cina', 'corea_del_sud', 'filippine', 'giappone', 'indonesia', 'laos', 'malesia', 'mongolia', 'myanmar', 'singapore', 'taiwan', 'thailandia', 'vietnam', 'arabia_saudita', 'emirati_arabi_uniti', 'giordania', 'iran', 'israele', 'libano', 'oman', 'qatar', 'antigua_e_barbuda', 'barbados', 'belize', 'costa_rica', 'cuba', 'giamaica', 'guatemala', 'honduras', 'messico', 'nicaragua', 'panama', 'repubblica_dominicana', 'saint_lucia', 'saint_vincent_e_grenadine', 'sint_maarten', 'canada', 'stati_uniti', 'argentina', 'bolivia', 'brasile', 'cile', 'colombia', 'ecuador', 'paraguay', 'peru', 'uruguay', 'venezuela', 'australia', 'fiji', 'isole_cook', 'nuova_zelanda', 'polinesia_francese', 'samoa', 'tonga', 'antartide']::text[])
  ) e;
  if v_extra is not null then
    raise exception 'Il database ha righe geografiche che xpetis_destinazioni_v2.json non ha più: %. Toglierle è una decisione, non una rigenerazione.', v_extra;
  end if;
end $$;

insert into geo_continents (code, name_it, is_selectable, sort_order) values
  ('europa', 'Europa', false, 1),
  ('africa', 'Africa', false, 2),
  ('asia', 'Asia', false, 3),
  ('americhe', 'Americhe', false, 4),
  ('oceania', 'Oceania', false, 5),
  ('antartide', 'Antartide', false, 6)
on conflict (code) do update set
  name_it = excluded.name_it, is_selectable = excluded.is_selectable, sort_order = excluded.sort_order;

insert into geo_macro_areas (code, continent_code, name_it, is_selectable, sort_order) values
  ('europa_est_e_caucaso', 'europa', 'Europa Est e Caucaso', true, 1),
  ('europa_nord', 'europa', 'Europa Nord', true, 2),
  ('europa_sud', 'europa', 'Europa Sud', true, 3),
  ('africa_sub_sahariana', 'africa', 'Africa Sub-Sahariana', true, 1),
  ('isole_delloceano_indiano', 'africa', 'Isole dell''Oceano Indiano', true, 2),
  ('nord_africa', 'africa', 'Nord Africa', true, 3),
  ('asia_centrale_e_subcontinente_indiano', 'asia', 'Asia Centrale e Subcontinente Indiano', true, 1),
  ('asia_orientale_e_sud_est_asiatico', 'asia', 'Asia Orientale e Sud-Est Asiatico', true, 2),
  ('medio_oriente', 'asia', 'Medio Oriente', true, 3),
  ('centro_america_e_caraibi', 'americhe', 'Centro America e Caraibi', true, 1),
  ('nord_america', 'americhe', 'Nord America', true, 2),
  ('sud_america', 'americhe', 'Sud America', true, 3),
  ('oceania', 'oceania', 'Oceania', true, 1),
  ('antartide', 'antartide', 'Antartide', true, 1)
on conflict (code) do update set
  continent_code = excluded.continent_code, name_it = excluded.name_it,
  is_selectable = excluded.is_selectable, sort_order = excluded.sort_order;

insert into geo_countries (code, macro_area_code, name_it, is_selectable, sort_order) values
  ('armenia', 'europa_est_e_caucaso', 'Armenia', true, 1),
  ('azerbaijan', 'europa_est_e_caucaso', 'Azerbaijan', true, 2),
  ('bielorussia', 'europa_est_e_caucaso', 'Bielorussia', true, 3),
  ('georgia', 'europa_est_e_caucaso', 'Georgia', true, 4),
  ('moldavia', 'europa_est_e_caucaso', 'Moldavia', true, 5),
  ('russia', 'europa_est_e_caucaso', 'Russia', true, 6),
  ('ucraina', 'europa_est_e_caucaso', 'Ucraina', true, 7),
  ('austria', 'europa_nord', 'Austria', true, 1),
  ('belgio', 'europa_nord', 'Belgio', true, 2),
  ('danimarca', 'europa_nord', 'Danimarca', true, 3),
  ('estonia', 'europa_nord', 'Estonia', true, 4),
  ('finlandia', 'europa_nord', 'Finlandia', true, 5),
  ('francia', 'europa_nord', 'Francia', true, 6),
  ('germania', 'europa_nord', 'Germania', true, 7),
  ('irlanda', 'europa_nord', 'Irlanda', true, 8),
  ('islanda', 'europa_nord', 'Islanda', true, 9),
  ('lettonia', 'europa_nord', 'Lettonia', true, 10),
  ('lituania', 'europa_nord', 'Lituania', true, 11),
  ('lussemburgo', 'europa_nord', 'Lussemburgo', true, 12),
  ('norvegia', 'europa_nord', 'Norvegia', true, 13),
  ('paesi_bassi', 'europa_nord', 'Paesi Bassi', true, 14),
  ('polonia', 'europa_nord', 'Polonia', true, 15),
  ('regno_unito', 'europa_nord', 'Regno Unito', true, 16),
  ('repubblica_ceca', 'europa_nord', 'Repubblica Ceca', true, 17),
  ('slovacchia', 'europa_nord', 'Slovacchia', true, 18),
  ('svezia', 'europa_nord', 'Svezia', true, 19),
  ('svizzera', 'europa_nord', 'Svizzera', true, 20),
  ('ungheria', 'europa_nord', 'Ungheria', true, 21),
  ('albania', 'europa_sud', 'Albania', true, 1),
  ('andorra', 'europa_sud', 'Andorra', true, 2),
  ('bosnia_ed_erzegovina', 'europa_sud', 'Bosnia ed Erzegovina', true, 3),
  ('bulgaria', 'europa_sud', 'Bulgaria', true, 4),
  ('cipro', 'europa_sud', 'Cipro', true, 5),
  ('croazia', 'europa_sud', 'Croazia', true, 6),
  ('grecia', 'europa_sud', 'Grecia', true, 7),
  ('italia', 'europa_sud', 'Italia', true, 8),
  ('kosovo', 'europa_sud', 'Kosovo', true, 9),
  ('macedonia_del_nord', 'europa_sud', 'Macedonia del Nord', true, 10),
  ('malta', 'europa_sud', 'Malta', true, 11),
  ('montenegro', 'europa_sud', 'Montenegro', true, 12),
  ('portogallo', 'europa_sud', 'Portogallo', true, 13),
  ('romania', 'europa_sud', 'Romania', true, 14),
  ('serbia', 'europa_sud', 'Serbia', true, 15),
  ('slovenia', 'europa_sud', 'Slovenia', true, 16),
  ('spagna', 'europa_sud', 'Spagna', true, 17),
  ('turchia', 'europa_sud', 'Turchia', true, 18),
  ('angola', 'africa_sub_sahariana', 'Angola', true, 1),
  ('botswana', 'africa_sub_sahariana', 'Botswana', true, 2),
  ('capo_verde', 'africa_sub_sahariana', 'Capo Verde', true, 3),
  ('costa_davorio', 'africa_sub_sahariana', 'Costa d''Avorio', true, 4),
  ('eritrea', 'africa_sub_sahariana', 'Eritrea', true, 5),
  ('etiopia', 'africa_sub_sahariana', 'Etiopia', true, 6),
  ('gambia', 'africa_sub_sahariana', 'Gambia', true, 7),
  ('ghana', 'africa_sub_sahariana', 'Ghana', true, 8),
  ('kenya', 'africa_sub_sahariana', 'Kenya', true, 9),
  ('mozambico', 'africa_sub_sahariana', 'Mozambico', true, 10),
  ('namibia', 'africa_sub_sahariana', 'Namibia', true, 11),
  ('nigeria', 'africa_sub_sahariana', 'Nigeria', true, 12),
  ('rwanda', 'africa_sub_sahariana', 'Rwanda', true, 13),
  ('senegal', 'africa_sub_sahariana', 'Senegal', true, 14),
  ('sudafrica', 'africa_sub_sahariana', 'Sudafrica', true, 15),
  ('tanzania', 'africa_sub_sahariana', 'Tanzania', true, 16),
  ('uganda', 'africa_sub_sahariana', 'Uganda', true, 17),
  ('zimbabwe', 'africa_sub_sahariana', 'Zimbabwe', true, 18),
  ('madagascar', 'isole_delloceano_indiano', 'Madagascar', true, 1),
  ('mauritius', 'isole_delloceano_indiano', 'Mauritius', true, 2),
  ('riunione', 'isole_delloceano_indiano', 'Riunione', true, 3),
  ('seychelles', 'isole_delloceano_indiano', 'Seychelles', true, 4),
  ('algeria', 'nord_africa', 'Algeria', true, 1),
  ('egitto', 'nord_africa', 'Egitto', true, 2),
  ('libia', 'nord_africa', 'Libia', true, 3),
  ('marocco', 'nord_africa', 'Marocco', true, 4),
  ('tunisia', 'nord_africa', 'Tunisia', true, 5),
  ('bangladesh', 'asia_centrale_e_subcontinente_indiano', 'Bangladesh', true, 1),
  ('bhutan', 'asia_centrale_e_subcontinente_indiano', 'Bhutan', true, 2),
  ('india', 'asia_centrale_e_subcontinente_indiano', 'India', true, 3),
  ('kazakistan', 'asia_centrale_e_subcontinente_indiano', 'Kazakistan', true, 4),
  ('kirghizistan', 'asia_centrale_e_subcontinente_indiano', 'Kirghizistan', true, 5),
  ('maldive', 'asia_centrale_e_subcontinente_indiano', 'Maldive', true, 6),
  ('nepal', 'asia_centrale_e_subcontinente_indiano', 'Nepal', true, 7),
  ('sri_lanka', 'asia_centrale_e_subcontinente_indiano', 'Sri Lanka', true, 8),
  ('uzbekistan', 'asia_centrale_e_subcontinente_indiano', 'Uzbekistan', true, 9),
  ('cambogia', 'asia_orientale_e_sud_est_asiatico', 'Cambogia', true, 1),
  ('cina', 'asia_orientale_e_sud_est_asiatico', 'Cina', true, 2),
  ('corea_del_sud', 'asia_orientale_e_sud_est_asiatico', 'Corea del Sud', true, 3),
  ('filippine', 'asia_orientale_e_sud_est_asiatico', 'Filippine', true, 4),
  ('giappone', 'asia_orientale_e_sud_est_asiatico', 'Giappone', true, 5),
  ('indonesia', 'asia_orientale_e_sud_est_asiatico', 'Indonesia', true, 6),
  ('laos', 'asia_orientale_e_sud_est_asiatico', 'Laos', true, 7),
  ('malesia', 'asia_orientale_e_sud_est_asiatico', 'Malesia', true, 8),
  ('mongolia', 'asia_orientale_e_sud_est_asiatico', 'Mongolia', true, 9),
  ('myanmar', 'asia_orientale_e_sud_est_asiatico', 'Myanmar', true, 10),
  ('singapore', 'asia_orientale_e_sud_est_asiatico', 'Singapore', true, 11),
  ('taiwan', 'asia_orientale_e_sud_est_asiatico', 'Taiwan', true, 12),
  ('thailandia', 'asia_orientale_e_sud_est_asiatico', 'Thailandia', true, 13),
  ('vietnam', 'asia_orientale_e_sud_est_asiatico', 'Vietnam', true, 14),
  ('arabia_saudita', 'medio_oriente', 'Arabia Saudita', true, 1),
  ('emirati_arabi_uniti', 'medio_oriente', 'Emirati Arabi Uniti', true, 2),
  ('giordania', 'medio_oriente', 'Giordania', true, 3),
  ('iran', 'medio_oriente', 'Iran', true, 4),
  ('israele', 'medio_oriente', 'Israele', true, 5),
  ('libano', 'medio_oriente', 'Libano', true, 6),
  ('oman', 'medio_oriente', 'Oman', true, 7),
  ('qatar', 'medio_oriente', 'Qatar', true, 8),
  ('antigua_e_barbuda', 'centro_america_e_caraibi', 'Antigua e Barbuda', true, 1),
  ('barbados', 'centro_america_e_caraibi', 'Barbados', true, 2),
  ('belize', 'centro_america_e_caraibi', 'Belize', true, 3),
  ('costa_rica', 'centro_america_e_caraibi', 'Costa Rica', true, 4),
  ('cuba', 'centro_america_e_caraibi', 'Cuba', true, 5),
  ('giamaica', 'centro_america_e_caraibi', 'Giamaica', true, 6),
  ('guatemala', 'centro_america_e_caraibi', 'Guatemala', true, 7),
  ('honduras', 'centro_america_e_caraibi', 'Honduras', true, 8),
  ('messico', 'centro_america_e_caraibi', 'Messico', true, 9),
  ('nicaragua', 'centro_america_e_caraibi', 'Nicaragua', true, 10),
  ('panama', 'centro_america_e_caraibi', 'Panama', true, 11),
  ('repubblica_dominicana', 'centro_america_e_caraibi', 'Repubblica Dominicana', true, 12),
  ('saint_lucia', 'centro_america_e_caraibi', 'Saint Lucia', true, 13),
  ('saint_vincent_e_grenadine', 'centro_america_e_caraibi', 'Saint Vincent e Grenadine', true, 14),
  ('sint_maarten', 'centro_america_e_caraibi', 'Sint Maarten', true, 15),
  ('canada', 'nord_america', 'Canada', true, 1),
  ('stati_uniti', 'nord_america', 'Stati Uniti', true, 2),
  ('argentina', 'sud_america', 'Argentina', true, 1),
  ('bolivia', 'sud_america', 'Bolivia', true, 2),
  ('brasile', 'sud_america', 'Brasile', true, 3),
  ('cile', 'sud_america', 'Cile', true, 4),
  ('colombia', 'sud_america', 'Colombia', true, 5),
  ('ecuador', 'sud_america', 'Ecuador', true, 6),
  ('paraguay', 'sud_america', 'Paraguay', true, 7),
  ('peru', 'sud_america', 'Perù', true, 8),
  ('uruguay', 'sud_america', 'Uruguay', true, 9),
  ('venezuela', 'sud_america', 'Venezuela', true, 10),
  ('australia', 'oceania', 'Australia', true, 1),
  ('fiji', 'oceania', 'Fiji', true, 2),
  ('isole_cook', 'oceania', 'Isole Cook', true, 3),
  ('nuova_zelanda', 'oceania', 'Nuova Zelanda', true, 4),
  ('polinesia_francese', 'oceania', 'Polinesia Francese', true, 5),
  ('samoa', 'oceania', 'Samoa', true, 6),
  ('tonga', 'oceania', 'Tonga', true, 7),
  ('antartide', 'antartide', 'Antartide', true, 1)
on conflict (code) do update set
  macro_area_code = excluded.macro_area_code, name_it = excluded.name_it,
  is_selectable = excluded.is_selectable, sort_order = excluded.sort_order;

-- Le città, agganciate al loro paese (dalla 0057 non ci sono regioni). Stanno
-- in una tabella temporanea perché servono due volte: per l'inserimento e
-- per la potatura. Il drop in testa rende il seed rilanciabile anche dopo un
-- giro fermato a metà.
drop table if exists geo_citta_attese;
create temp table geo_citta_attese (
  country_code text, city_slug text, city_name text, is_selectable boolean
);
insert into geo_citta_attese values
  ('armenia', 'yerevan', 'Yerevan', false),
  ('azerbaijan', 'baku', 'Baku', false),
  ('bielorussia', 'minsk', 'Minsk', false),
  ('georgia', 'tbilisi', 'Tbilisi', false),
  ('moldavia', 'chișinău', 'Chișinău', false),
  ('russia', 'mosca', 'Mosca', false),
  ('russia', 'san_pietroburgo', 'San Pietroburgo', false),
  ('ucraina', 'kiev', 'Kiev', false),
  ('austria', 'vienna', 'Vienna', false),
  ('belgio', 'bruxelles', 'Bruxelles', false),
  ('danimarca', 'copenaghen', 'Copenaghen', false),
  ('estonia', 'tallinn', 'Tallinn', false),
  ('finlandia', 'helsinki', 'Helsinki', false),
  ('francia', 'parigi', 'Parigi', false),
  ('francia', 'nizza', 'Nizza', false),
  ('germania', 'monaco', 'Monaco', false),
  ('germania', 'berlino', 'Berlino', false),
  ('irlanda', 'dublino', 'Dublino', false),
  ('islanda', 'reykjavik', 'Reykjavik', false),
  ('lettonia', 'riga', 'Riga', false),
  ('lituania', 'vilnius', 'Vilnius', false),
  ('lussemburgo', 'lussemburgo_citta', 'Lussemburgo Città', false),
  ('norvegia', 'oslo', 'Oslo', false),
  ('norvegia', 'bergen', 'Bergen', false),
  ('paesi_bassi', 'amsterdam', 'Amsterdam', false),
  ('polonia', 'varsavia', 'Varsavia', false),
  ('polonia', 'cracovia', 'Cracovia', false),
  ('regno_unito', 'londra', 'Londra', false),
  ('regno_unito', 'edimburgo', 'Edimburgo', false),
  ('repubblica_ceca', 'praga', 'Praga', false),
  ('slovacchia', 'bratislava', 'Bratislava', false),
  ('svezia', 'stoccolma', 'Stoccolma', false),
  ('svizzera', 'ginevra', 'Ginevra', false),
  ('svizzera', 'zurigo', 'Zurigo', false),
  ('ungheria', 'budapest', 'Budapest', false),
  ('albania', 'tirana', 'Tirana', false),
  ('bosnia_ed_erzegovina', 'sarajevo', 'Sarajevo', false),
  ('bulgaria', 'sofia', 'Sofia', false),
  ('cipro', 'nicosia', 'Nicosia', false),
  ('croazia', 'dubrovnik', 'Dubrovnik', false),
  ('grecia', 'atene', 'Atene', false),
  ('grecia', 'santorini', 'Santorini', false),
  ('italia', 'laquila', 'L''Aquila', false),
  ('italia', 'matera', 'Matera', false),
  ('italia', 'reggio_calabria', 'Reggio Calabria', false),
  ('italia', 'napoli', 'Napoli', false),
  ('italia', 'bologna', 'Bologna', false),
  ('italia', 'trieste', 'Trieste', false),
  ('italia', 'roma', 'Roma', false),
  ('italia', 'genova', 'Genova', false),
  ('italia', 'milano', 'Milano', false),
  ('italia', 'ancona', 'Ancona', false),
  ('italia', 'campobasso', 'Campobasso', false),
  ('italia', 'torino', 'Torino', false),
  ('italia', 'bari', 'Bari', false),
  ('italia', 'cagliari', 'Cagliari', false),
  ('italia', 'palermo', 'Palermo', false),
  ('italia', 'firenze', 'Firenze', false),
  ('italia', 'trento', 'Trento', false),
  ('italia', 'perugia', 'Perugia', false),
  ('italia', 'aosta', 'Aosta', false),
  ('italia', 'venezia', 'Venezia', false),
  ('kosovo', 'pristina', 'Pristina', false),
  ('macedonia_del_nord', 'skopje', 'Skopje', false),
  ('malta', 'la_valletta', 'La Valletta', false),
  ('montenegro', 'kotor', 'Kotor', false),
  ('portogallo', 'lisbona', 'Lisbona', false),
  ('portogallo', 'porto', 'Porto', false),
  ('romania', 'bucarest', 'Bucarest', false),
  ('serbia', 'belgrado', 'Belgrado', false),
  ('slovenia', 'lubiana', 'Lubiana', false),
  ('spagna', 'barcellona', 'Barcellona', false),
  ('spagna', 'madrid', 'Madrid', false),
  ('turchia', 'istanbul', 'Istanbul', false),
  ('botswana', 'okavango_delta', 'Okavango Delta', false),
  ('capo_verde', 'praia', 'Praia', false),
  ('costa_davorio', 'abidjan', 'Abidjan', false),
  ('etiopia', 'addis_abeba', 'Addis Abeba', false),
  ('ghana', 'accra', 'Accra', false),
  ('kenya', 'nairobi', 'Nairobi', false),
  ('mozambico', 'maputo', 'Maputo', false),
  ('namibia', 'windhoek', 'Windhoek', false),
  ('nigeria', 'lagos', 'Lagos', false),
  ('rwanda', 'kigali', 'Kigali', false),
  ('senegal', 'dakar', 'Dakar', false),
  ('sudafrica', 'citta_del_capo', 'Città del Capo', false),
  ('sudafrica', 'johannesburg', 'Johannesburg', false),
  ('tanzania', 'dar_es_salaam', 'Dar es Salaam', false),
  ('tanzania', 'stone_town', 'Stone Town', false),
  ('uganda', 'kampala', 'Kampala', false),
  ('zimbabwe', 'harare', 'Harare', false),
  ('zimbabwe', 'victoria_falls', 'Victoria Falls', false),
  ('madagascar', 'antananarivo', 'Antananarivo', false),
  ('mauritius', 'port_louis', 'Port Louis', false),
  ('riunione', 'saint_denis', 'Saint-Denis', false),
  ('seychelles', 'victoria', 'Victoria', false),
  ('algeria', 'algeri', 'Algeri', false),
  ('egitto', 'il_cairo', 'Il Cairo', false),
  ('egitto', 'luxor', 'Luxor', false),
  ('libia', 'tripoli', 'Tripoli', false),
  ('marocco', 'marrakech', 'Marrakech', false),
  ('marocco', 'casablanca', 'Casablanca', false),
  ('tunisia', 'tunisi', 'Tunisi', false),
  ('bhutan', 'thimphu', 'Thimphu', false),
  ('india', 'delhi', 'Delhi', false),
  ('india', 'agra', 'Agra', false),
  ('kazakistan', 'almaty', 'Almaty', false),
  ('kirghizistan', 'bishkek', 'Bishkek', false),
  ('maldive', 'male', 'Malé', false),
  ('nepal', 'kathmandu', 'Kathmandu', false),
  ('sri_lanka', 'colombo', 'Colombo', false),
  ('uzbekistan', 'samarcanda', 'Samarcanda', false),
  ('cambogia', 'phnom_penh', 'Phnom Penh', false),
  ('cambogia', 'siem_reap', 'Siem Reap', false),
  ('cina', 'pechino', 'Pechino', false),
  ('cina', 'shanghai', 'Shanghai', false),
  ('cina', 'hong_kong', 'Hong Kong', false),
  ('corea_del_sud', 'seoul', 'Seoul', false),
  ('filippine', 'manila', 'Manila', false),
  ('giappone', 'tokyo', 'Tokyo', false),
  ('giappone', 'kyoto', 'Kyoto', false),
  ('giappone', 'osaka', 'Osaka', false),
  ('indonesia', 'ubud', 'Ubud', false),
  ('indonesia', 'jakarta', 'Jakarta', false),
  ('laos', 'luang_prabang', 'Luang Prabang', false),
  ('malesia', 'kuala_lumpur', 'Kuala Lumpur', false),
  ('mongolia', 'ulaanbaatar', 'Ulaanbaatar', false),
  ('myanmar', 'yangon', 'Yangon', false),
  ('singapore', 'marina_bay', 'Marina Bay', false),
  ('taiwan', 'taipei', 'Taipei', false),
  ('thailandia', 'bangkok', 'Bangkok', false),
  ('thailandia', 'phuket', 'Phuket', false),
  ('vietnam', 'hanoi', 'Hanoi', false),
  ('vietnam', 'ho_chi_minh_city', 'Ho Chi Minh City', false),
  ('arabia_saudita', 'riad', 'Riad', false),
  ('arabia_saudita', 'jeddah', 'Jeddah', false),
  ('emirati_arabi_uniti', 'dubai', 'Dubai', false),
  ('emirati_arabi_uniti', 'abu_dhabi', 'Abu Dhabi', false),
  ('giordania', 'amman', 'Amman', false),
  ('iran', 'teheran', 'Teheran', false),
  ('israele', 'gerusalemme', 'Gerusalemme', false),
  ('israele', 'tel_aviv', 'Tel Aviv', false),
  ('libano', 'beirut', 'Beirut', false),
  ('oman', 'muscat', 'Muscat', false),
  ('qatar', 'doha', 'Doha', false),
  ('belize', 'belize_city', 'Belize City', false),
  ('costa_rica', 'san_jose', 'San José', false),
  ('cuba', 'lavana', 'L''Avana', false),
  ('giamaica', 'kingston', 'Kingston', false),
  ('guatemala', 'citta_del_guatemala', 'Città del Guatemala', false),
  ('honduras', 'tegucigalpa', 'Tegucigalpa', false),
  ('messico', 'cancún', 'Cancún', false),
  ('messico', 'citta_del_messico', 'Città del Messico', false),
  ('nicaragua', 'managua', 'Managua', false),
  ('panama', 'panama_city', 'Panama City', false),
  ('repubblica_dominicana', 'santo_domingo', 'Santo Domingo', false),
  ('canada', 'toronto', 'Toronto', false),
  ('canada', 'vancouver', 'Vancouver', false),
  ('stati_uniti', 'new_york', 'New York', false),
  ('stati_uniti', 'washington_dc', 'Washington DC', false),
  ('stati_uniti', 'miami', 'Miami', false),
  ('stati_uniti', 'los_angeles', 'Los Angeles', false),
  ('stati_uniti', 'san_francisco', 'San Francisco', false),
  ('stati_uniti', 'las_vegas', 'Las Vegas', false),
  ('stati_uniti', 'chicago', 'Chicago', false),
  ('stati_uniti', 'honolulu', 'Honolulu', false),
  ('argentina', 'buenos_aires', 'Buenos Aires', false),
  ('bolivia', 'la_paz', 'La Paz', false),
  ('brasile', 'rio_de_janeiro', 'Rio de Janeiro', false),
  ('brasile', 'san_paolo', 'San Paolo', false),
  ('cile', 'santiago', 'Santiago', false),
  ('colombia', 'bogotá', 'Bogotá', false),
  ('colombia', 'cartagena', 'Cartagena', false),
  ('ecuador', 'quito', 'Quito', false),
  ('paraguay', 'asunción', 'Asunción', false),
  ('peru', 'lima', 'Lima', false),
  ('peru', 'cusco', 'Cusco', false),
  ('uruguay', 'montevideo', 'Montevideo', false),
  ('venezuela', 'caracas', 'Caracas', false),
  ('australia', 'sydney', 'Sydney', false),
  ('australia', 'melbourne', 'Melbourne', false),
  ('fiji', 'nadi', 'Nadi', false),
  ('isole_cook', 'rarotonga', 'Rarotonga', false),
  ('nuova_zelanda', 'auckland', 'Auckland', false),
  ('nuova_zelanda', 'queenstown', 'Queenstown', false),
  ('polinesia_francese', 'bora_bora', 'Bora Bora', false),
  ('samoa', 'apia', 'Apia', false),
  ('tonga', 'nukualofa', 'Nuku''alofa', false);

insert into geo_cities (country_code, slug, name_it, is_selectable)
select v.country_code, v.city_slug, v.city_name, v.is_selectable
  from geo_citta_attese v
on conflict (country_code, slug) do update set
  name_it = excluded.name_it, is_selectable = excluded.is_selectable;

-- La potatura: le città che il file non ha più se ne vanno. Nessuna chiave
-- esterna punta a geo_cities (verificato il 27 settembre 2026), quindi non
-- trascina niente con sé. Su un database vuoto non fa nulla.
delete from geo_cities c
 where not exists (select 1 from geo_citta_attese v
                    where v.country_code = c.country_code and v.city_slug = c.slug);

drop table geo_citta_attese;

commit;
